### ISSUE TITLE
Removing an item from a list

### ISSUE THREAD

**Issue by luto** [kwoodson/yedit#14]
``` yml
- name: remove apples from the grocery list
  yedit:
    state: absent
    index: 1
    key: groceries
    content: { 'groceries': [ 'oranges', 'apples' ] }
  register: res
- debug: var=res
```

I would expect `res.result` to be equal to `{ 'groceries': [ 'oranges' ] }`, instead it's just `null`. It seems like `absent` ignores the `index` parameter entirely and just deletes the whole `groceries` key.

@kwoodson can you confirm that `{ 'groceries': [ 'oranges' ] }` is the expected value here? If so, I'll prepare a PR.

**Comment by kwoodson** [comment]
`#!/usr/bin/ansible-playbook`
`---`
`- hosts: localhost`
`  gather_facts: no`
`  tasks:`
`  - yedit:`
`      state: absent`
`      update: True`
`      key: groceries`
`      value: apples`
`      content:`
`        groceries:`
`        - oranges`
`        - apples`
`    register: res`
 ` - debug: var=res`


https://github.com/kwoodson/yedit/pull/15/files

**Comment by luto** [comment]
It seems like my original report wasn't very clear. So, the following example works. It converts `[ 'oranges', 'apples' ]` to `[ 'oranges', 'kiwi' ]`, by replacing a single item within an array.

```yml
    - name: replace apples by kiwi
      yedit:
        update: yes
        index: 1
        value: 'kiwi'
        content: [ 'oranges', 'apples' ]
      register: res
    - set_fact: res={{ res.result }}
    - assert:
        that:
          - res|length == 2
          - res == [ 'oranges', 'kiwi' ]
```

Since I can change items within a list using `index` and `update: yes`, I expect to also be able to delete items from said list:

```yml
    - name: remove apples from the grocery list, by index
      yedit:
        state: absent
        update: yes
        index: 1
        content: [ 'oranges', 'apples' ]
      register: res
    - set_fact: res={{ res.result }}
    - assert:
        that:
          - res|length == 1
          - res == [ 'oranges' ]
```

The thing is that the code for `absent` do not look at the `index` value _at all_ at the moment. It only cares about the `key`.

Using your patch in #15 the 2nd example just leaves the list untouched, without the patch the whole array is set to `null`. So it makes things better and fixes a couple other bugs when editing in-memory. The `index` is still not evaluated, though: the code generates `[ 'oranges', 'apples' ]` instead of `[ 'oranges' ]`.

Once your PR is merged, I'll prepare one to take the index into account, too.
