### ISSUE TITLE
Defaulting to an empty list with `append=true`

### ISSUE THREAD

**Issue by luto** [kwoodson/yedit#17]
Assuming `some.yml` is empty or at least does not yet contain the key `domains`, the following yml does nothing:

```yml
- name: Add default domain
  yedit:
    src: some.yml
    key: domains
    append: yes
    value: "google.com"
```

To my knowledge, there is no way to easily default `domains` to an empty array, when the state of the file in unknown to begin with. The current code for [`yedit.append()`](https://github.com/kwoodson/yedit/blob/master/roles/lib_yaml_editor/build/src/yedit.py#L307-L319) explicitly aborts, when the key is not found. It also aborts, when the key is of some other type, which makes sense.

I would like the change the behavior within `yedit.append()`, so that if the key does not yet exist, so it defaults to an empty array, to which the new value is added.

@kwoodson what are your thoughts on this?
