### ISSUE TITLE
Supplying a dict as value to a key/value yedit-call

### ISSUE THREAD

**Issue by luto** [kwoodson/yedit#3]
On my system with ansible 2.1.1.0 the following playbook generates - in my opinion - not the expected yml.

**Playbook**
```yml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: manage yaml files
    yedit:
      src: /tmp/test1.yaml
      key: a
      value:
        d:
          this is a test
```
This playbook is a simplified example from the projects README-file.

**Generated yml**
```yml
a: '{''d'': ''this is a test''}'
```
Note that there is no yml-dictionary within `a` here. There is just a string containing a JSON/YML-dictionary.

**Expected yml**
```yml
a:
  d: this is a test
```

Is this the correct behavior?

**Comment by kwoodson** [comment]
@luto,

Ansible 1.9 would preprocess your inputs and call a yaml.load on them.  In ansible 2.x, I have been seeing that it will pass you the string representation of your parameter.  I have added a yaml.load to fix this issue.  I have tested this and it appeared to work.

Please test with the latest changes that I have pushed and verify if this behavior continues.

**Comment by luto** [comment]
The behavior of `value` is fixed now. It seems like `content` has the same bug?

This task
```yml
  - name: test creation with content as dict
    yedit:
      src: noexistdict.yml
      content:
        a: test
        b: test
```
(from the [yedit test files](https://github.com/kwoodson/yedit/blob/master/roles/lib_yaml_editor/build/test/test.yaml#L47-L55))

Produces the following yml:

```yml
'{''a'': ''test'', ''b'': ''test''}'
```

I've created [a new PR](https://github.com/kwoodson/yedit/pull/4) to fix this. Please let me know, if that works for you, too. It just uses the same `parse_value` function you used for `value`.
