### ISSUE TITLE
Integer coming through as String

### ISSUE THREAD

**Issue by alaverty** [kwoodson/yedit#36]
With yedit ansible task like this :

```
    yedit:
      src: "zones/my_dns_zone.yaml"
      key: "pilot1"
      value:
        ttl: "60"
        type: "A"
        value: "10.1.1.1"
```
i get Yaml output like this where the integer 60 is a string :

```
pilot1:
  ttl: '60'
  type: A
  value: 10.1.1.1
```

how do I get it so the ttl comes out as an integer like so :

```
pilot1:
  ttl: 60
  type: A
  value: 10.1.1.1
```

**Comment by kwoodson** [comment]
If you quote a value inside of yaml it is specifically told that it should be a string.  Yaml doesn't require you to quote strings or ints unless there are `:` or other special characters.

This worked fine for me:
```yaml
#!/usr/bin/ansible-playbook
#---
- hosts: localhost
  gather_facts: no
  tasks:
  - import_role:
      name: /home/kwoodson/git/yedit/roles/lib_yaml_editor
      #name: /home/kwoodson/git/openshift-ansible/roles/lib_utils

  - yedit:
      src: /home/kwoodson/tmp/test_data.yml
      key: pilot1
      value:
        ttl: 60
        type: A
        value: "10.1.1.1"

  - yedit:
      src: /home/kwoodson/tmp/test_data.yml
      state: list
      key: pilot1
    register: rval

  - debug:
      msg: "{{ rval.result.ttl }}"

  - debug:
      msg: "{{ rval.result.ttl | type_debug }}"
```



Results:
```

PLAY [localhost] ***************************************************************************************************************************

TASK [yedit] *******************************************************************************************************************************
ok: [localhost]

TASK [yedit] *******************************************************************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": "60"
}

TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": "int"
}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```
