### ISSUE TITLE
allow prepending to a list

### ISSUE THREAD

**Issue by luto** [kwoodson/yedit#9]
Simmilar to `append: yes` there should be a `prepend: yes` to add something as the first entry on a list.

```yaml
- name: add oranges to the end, because they are kinda meh
  yedit:
    append: yes
    content: [ 'kiwi', 'peppers' ]
    value: oranges
# generates: [ 'kiwi', 'peppers', 'oranges' ]

- name: add apples before everything else, because they are AWESOME
  yedit:
    prepend: yes
    content: [ 'kiwi', 'peppers' ]
    value: apples
# generates: [ 'apples', 'kiwi', 'peppers' ]
```

- [ ] implement `yedit.prepend` and [its tests](https://github.com/kwoodson/yedit/blob/55720cb045fd1f400b04bfec12f8ee7731a685bb/test/units/yedit_test.py#L182), simmilar to the existing [`yedit.append`](https://github.com/kwoodson/yedit/blob/55720cb045fd1f400b04bfec12f8ee7731a685bb/roles/lib_yaml_editor/build/src/yedit.py#L279-L291)
- [ ] add the mutually exclusive `prepend` parameter to the [ansible parameters](https://github.com/kwoodson/yedit/blob/55720cb045fd1f400b04bfec12f8ee7731a685bb/roles/lib_yaml_editor/build/ansible/yedit.py#L63) and write the necessary glue-code
- [ ] add [parameter documentation](https://github.com/kwoodson/yedit/blob/55720cb045fd1f400b04bfec12f8ee7731a685bb/roles/lib_yaml_editor/build/doc/yedit#L64)
- [ ] add an example to the readme
